### ISSUE TITLE
Add version catalogs

### ISSUE THREAD

**Issue by shalva97** [Wavesonics/compose-multiplatform-file-picker#12]
I think version catalogs are much cleaner way to keep versions. For example [here is a catalog from my app](https://github.com/Nodrex/Testomania/blob/main/gradle/libs.versions.toml)

```toml
[versions]
minSdk = "24"
targetSdk = "33"
compileSdk = "33"
versionCode = "9"
versionName = "1.3.1"
composeCompiler = "1.2.0"

[libraries]
kiwi-icons = "kiwi.orbit.compose:icons:0.24.0"
kiwi-ui = "kiwi.orbit.compose:ui:0.24.0"
kiwi-illustrations = "kiwi.orbit.compose:illustrations:0.24.0"

androidx-compose-navigation-hilt = "androidx.hilt:hilt-navigation-compose:1.0.0"
androidx-compose-foundation = "androidx.compose.foundation:foundation:1.3.1"
androidx-compose-viewmodel-lifecycle = "androidx.lifecycle:lifecycle-viewmodel-compose:2.6.1"
androidx-compose-ui = "androidx.compose.ui:ui:1.3.3"
androidx-compose-material = "androidx.compose.material:material:1.3.1"
androidx-compose-material-icons-extended = "androidx.compose.material:material-icons-extended:1.3.1"
androidx-compose-constraintlayout = "androidx.constraintlayout:constraintlayout-compose:1.0.1"
androidx-tooling = "androidx.compose.ui:ui-tooling:1.3.3"
androidx-tooling-preview = "androidx.compose.ui:ui-tooling-preview:1.3.3"

raamcosta-destinations = 'io.github.raamcosta.compose-destinations:core:1.4.4-beta'
raamcosta-destinations-animations = 'io.github.raamcosta.compose-destinations:animations-core:1.4.4-beta'
raamcosta-destinations-ksp = 'io.github.raamcosta.compose-destinations:ksp:1.4.4-beta'

[bundles]
kiwi = [
    "kiwi-icons",
    "kiwi-ui",
    "kiwi-illustrations"
]

androidx = [
    "androidx-lifecycle",
    "androidx-compose-activity",
    "androidx-datastore-preferences",
    "androidx-datastore-core",
    "androidx-datastore",
    "androidx-core",
    "androidx-appcompat",
    "androidx-room-runtime",
    "androidx-room-ktx",
]
```
